// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Projekt2025.Models;

[Table("Calendar")]
public partial class Calendar
{
    [Key]
    [Column("CalendarID")]
    public int CalendarId { get; set; }

    [Column("EventID")]
    public int EventId { get; set; }

    [ForeignKey("EventId")]
    [InverseProperty("Calendars")]
    public virtual Event Event { get; set; }
}