// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Projekt2025.Models;

public partial class Event
{
    [Key]
    [Column("EventID")]
    public int EventId { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Title { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime EventDateTimeStart { get; set; }

    [Required]
    [StringLength(200)]
    [Unicode(false)]
    public string Description { get; set; }

    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string Location { get; set; }

    public int Price { get; set; }

    public int Participants { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime EventDateTimeEnd { get; set; }

    [InverseProperty("Event")]
    public virtual ICollection<Calendar> Calendars { get; set; } = new List<Calendar>();
}