// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Projekt2025.Models;

[Table("Login")]
[Index("Username", Name = "UQ__Login__536C85E40907A96E", IsUnique = true)]
public partial class Login
{
    [Key]
    [Column("AccountID")]
    public int AccountId { get; set; }

    [Required]
    [StringLength(30)]
    [Unicode(false)]
    public string Username { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    public string Password { get; set; }

    [Column("MemberID")]
    public int MemberId { get; set; }

    [ForeignKey("MemberId")]
    [InverseProperty("Logins")]
    public virtual Member Member { get; set; }
}