// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Projekt2025.Models;

[Table("Member")]
public partial class Member
{
    [Key]
    [Column("MemberID")]
    public int MemberId { get; set; }

    [Required]
    [StringLength(30)]
    [Unicode(false)]
    public string Name { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Email { get; set; }

    [Required]
    [StringLength(15)]
    [Unicode(false)]
    public string Phone { get; set; }

    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string Address { get; set; }

    [Column("StudyID")]
    public int StudyId { get; set; }

    [InverseProperty("Member")]
    public virtual ICollection<Login> Logins { get; set; } = new List<Login>();

    [ForeignKey("StudyId")]
    [InverseProperty("Members")]
    public virtual StudyProgram Study { get; set; }
}