// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Projekt2025.Models;

[Index("Email", Name = "UQ__Newslett__A9D105342FBABAD6", IsUnique = true)]
public partial class NewsletterSub
{
    [Key]
    [Column("MemberID")]
    public int MemberId { get; set; }

    [Required]
    [StringLength(255)]
    public string Email { get; set; }

    public bool IsActive { get; set; }

    [ForeignKey("MemberId")]
    [InverseProperty("NewsletterSub")]
    public virtual Member Member { get; set; }
}