// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Projekt2025.Models;

public partial class NewsletterSub
{
    [Key]
    [StringLength(255)]
    public string Email { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? SubscribedAt { get; set; }

    public bool IsActive { get; set; }
}