// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Projekt2025.Models;

[Table("StudyProgram")]
[Index("Name", Name = "UQ__StudyPro__737584F6FAEB0937", IsUnique = true)]
public partial class StudyProgram
{
    [Key]
    [Column("StudyID")]
    public int StudyId { get; set; }

    [Required]
    [StringLength(30)]
    [Unicode(false)]
    public string Name { get; set; }

    [InverseProperty("Study")]
    public virtual ICollection<Member> Members { get; set; } = new List<Member>();
}